[project]
name = "telltale"
version = "0.1.0"
description = "A diagnostic system using natural language"
requires-python = ">=3.10"

dependencies = [
    "marvin>=2.0.0,<3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 
